table products
	lineageTag: b3220feb-40c8-4090-8f3b-cf6d526c273e

	column product
		dataType: string
		lineageTag: d866883f-7ebb-42db-9f3e-adc851d1509a
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column series
		dataType: string
		lineageTag: a6046fd0-63f5-4576-817b-4716dbf66164
		summarizeBy: none
		sourceColumn: series

		annotation SummarizationSetBy = Automatic

	column sales_price
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: e3c65cc8-9bcd-445c-9395-15eb85c5e435
		summarizeBy: none
		sourceColumn: sales_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jos_m\Desktop\mavenCRM\products.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product", type text}, {"series", type text}, {"sales_price", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

